CRITICAL:root:Use cached train data
CRITICAL:root:fitting model
CRITICAL:root:Use cached test data
CRITICAL:root:Creating new train pkl data file
ERROR:root:
ERROR FOR RUN: 110593bf5d66449eae1b18e419cfcbd2
ERROR:root:incompatible dimensions for cross product
(dimension must be 2 or 3)
Traceback (most recent call last):
  File "run.py", line 78, in run_pipe
    train = sv.vectorize(train, vectorizer_name=VECTORIZER_NAME)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 180, in vectorize
    data = self.vectorize_sent_ft(data, use_facebook_ft=True)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 97, in vectorize_sent_ft
    data[feat_col+'_vec'] = data[feat_col].progress_apply(lambda x: sent2vec(x))
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tqdm/std.py", line 810, in inner
    return getattr(df, df_function)(wrapper, **kwargs)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/pandas/core/series.py", line 4213, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tqdm/std.py", line 805, in wrapper
    return func(*args, **kwargs)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 97, in <lambda>
    data[feat_col+'_vec'] = data[feat_col].progress_apply(lambda x: sent2vec(x))
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 95, in sent2vec
    sent_vec = aggregate(sent, AGG_TYPE)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 91, in aggregate
    sent = reduce(lambda v1, v2: np.cross(v1, v2), vecs)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/data/sentence_vectorizer.py", line 91, in <lambda>
    sent = reduce(lambda v1, v2: np.cross(v1, v2), vecs)
  File "<__array_function__ internals>", line 6, in cross
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 1580, in cross
    raise ValueError(msg)
ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)
CRITICAL:root:Use cached train data
CRITICAL:root:fitting model
