ERROR:root:
ERROR FOR RUN: fe1700d1a5944194ad7061d1ae4972fe
ERROR:root:Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
Traceback (most recent call last):
  File "run.py", line 69, in run_pipe
    trainer.train_model(X_train, y_train)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/purpose_models/trainer.py", line 52, in train_model
    self.model.fit(X, y)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/purpose_models/model_svc.py", line 59, in fit
    self.model = self.get_best_model_configuration(X, y)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/purpose_models/model_svc.py", line 30, in get_best_model_configuration
    self.metric_learner.fit(X, y)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/support_models/metric_learner.py", line 20, in fit
    self.learner.fit(X, y)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/support_models/siamese_metric_learner.py", line 47, in fit
    steps_per_epoch=STEPS_PER_EPOCH,
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1861, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1064, in fit
    steps_per_execution=self._steps_per_execution)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1112, in __init__
    model=model)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 779, in __init__
    peek, x = self._peek_and_restore(x)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 836, in _peek_and_restore
    peek = next(x)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/support_models/triplet_generator.py", line 96, in generate_triplets
    a, p, n = self.get_triplet(X, y)
  File "/home/kaigorodov/myprojects/MedConcNorm/src/support_models/triplet_generator.py", line 80, in get_triplet
    anchor_x_idx = np.random.choice(X[y==anchor_y].shape[0])
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2897, in __getitem__
    return self._getitem_bool_array(key)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2949, in _getitem_bool_array
    key = check_bool_indexer(self.index, key)
  File "/home/kaigorodov/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2183, in check_bool_indexer
    "Unalignable boolean Series provided as "
pandas.core.indexing.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
